### ISSUE TITLE
Design Docs #1

### ISSUE THREAD

**Issue by rlim92** [ericsmith9161/Szyslak#1]
Szyslaaak! Great details on your design docs so far Eric. Got some thoughts below. 

**MVP List**
- [x] all of the extra UI features (emojis, links, files, text-styling, reminders) along with threads should be considered a bonus feature to add to `Live Chat` after the 4 core features have been fully implemented. 
- [x] recently viewed channels can be a bonus feature to add later.
- [x] make channels the first MVP after User Auth and then work on Live Chat.

**Schema**
- [x] `avatar_path` can be taken out. Use AWS for avatar hosting. 
- [x] `threads`, `emotes`, `drafts`, and `saved_messages` should be bonus and tackled after the 4 core features. 
- [x] for `saved_messages` depends on what `saved_messages` should be. If it is just a collection of saved messages available to the user, a joins table joining `saved_messages` and `messages` tables to achieve a many-to-many relationship is needed. Then, can use through association to use getter `message_ids` from a `SavedMessage` instance to get a reference to all the saved messages. Then, when rendering can re-use a message-item component to easily render on the front end. We can talk more in detail about this later but consider this a feature to complete after making channels and DMs. 
- [x] consider combining `user_channels` and `user_dm_conversations` into one polymorphic joins table. The functionality of both are essentially the same as basically a subscription or membership to the chat room.

**Comment by ericsmith9161** [comment]
Thanks Rich, good call on the combo-table!
