### ISSUE TITLE
Design Docs Sample State Review

### ISSUE THREAD

**Issue by rlim92** [ericsmith9161/Szyslak#2]
Hey Eric! I added a small suggestion to the schema just beforehand. Sample state looks really good. Some tips below.

**Sample State**
- [x] `users` may not need `messages` as a key as most times messages are only rendered when in a channel or DM. If you plan to add feature of showing all a user's messages, this may come in handy but messages will pile up fast and should be loaded only as needed (only when a message log is rendered). 
- [x] `user_channels` and `user_dm_conversations` are not needed as a slice of state because `channels` and `dms` both have a key of `users` that has all the information we need from those joins tables. 
- [x] added to the schema review but consider combining `user_channels` and `user_dm_conversations` into a polymorphic joins table.
- [x] in `errors` most likely wont need an error message for empty messages b/c Slack doesn't. Can just have in handleSubmit to just return if the value is an empty "", making it a no-op.
- [x] in `saved_messages` rather than save a `message_path` just save a `message_ids` key. if each key is supposed to represent a single message than can be saved as `message_id` or `message` and reference a message id.

**Comment by ericsmith9161** [comment]
Hi Rich, I thought `users` might want messages in order to incorporate message search later on, but I can relegate that to the bonus section for sure. 

All your suggestions make a lot of sense though! Thank you for looking things through.

Any ideas on how the "messageable" quality might show up in the state? I couldn't quite figure it out.

**Comment by rlim92** [comment]
Hey Eric,

Yeah totally keep it in there if you want to use it for later. 

For the `messageable` there are two options:
- In the jbuilder view, you can have conditional logic (remember u can use ruby in the jbuilder) that would set a key of `channel`/`channel_id` OR `dm`/`dm_id` depending on the `msg_instance.messageable_type` and setting the value as the `msg_instance.messageable_id`. 
- Send both `messageable_type` and `messageable_id` up in the jbuilder view and have conditional logic in the reducer. 

I recommend the first option as formatting the data beforehand in the jbuilder can make front end logic much cleaner.
