### ISSUE TITLE
Design Docs Review #3

### ISSUE THREAD

**Issue by rlim92** [ericsmith9161/Szyslak#3]
Hey Eric! Extremely well-detailed routes. Some suggestions below:

**Frontend Routes**
- [x] make sure to have `/` be for not logged in users and render a `Splash` component similar to Slack's page when not logged in (use incognito mode to quickly see when not logged in).
- [x] `/channels/:channelId/edit` may be unnecessary (depending on how many features channels have). If you want to edit the description it will need that right bar OR u can have all features be a clickable-modal right under the channel title (ex. pinned, add a topic, etc.). Same can be done for DM (minus `description`).
- [x] `/messages/:messageId` how much functionality are you looking for? if you want to be able to click a single message and render a new page (or to the side like slack threads) this may be necessary, otherwise i would consider this portion bonus for now. 
- [x] `/messages/new` no need for this route we can just have a MessageForm render at the bottom of a `Channel/DM` show page. 
- [x] `/messages/:messageId/edit` this can just be a modal component that pops up on click. (no changing routes).

**Backend Routes**
- [x] for grabbing single users `GET /api/channels/:channel_id/users/:id` routes with two wildcards are unnecessary. can just do regular `show` route and just include the user. Unless other plans are necessary where the channelId is needed. 
- [x] no need for the `user_subscriptions` routes. This is purely a joins table so can use through associations to grab in jbuilder (all we really need is the other end of the sub info).

**Comment by ericsmith9161** [comment]
Hi Rich, I've implemented all suggestions here - thanks for looking over my routes!

I was wondering if you had a similar tip to the splash page on for figuring out how to see the create/edit channel form - I tried to create one on the app academy channel but had no luck.

**Comment by rlim92** [comment]
Hey Eric, so Slack is a little bit unique in that the sign up form requires making a workspace so just reference the login form for the sign up. To reach the login form go to incognito and click `sign in` then enter `app-academy-open` as your workplace and you will see a login form. Use that as the reference. You do not need to include the workplace part of the form.
