### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by ericsmith9161** [ericsmith9161/Szyslak#4]
Hi Rich, I'm creating an issue for an MVP review of User Auth, I've attached my MVP stuff underneath to make checking stuff easier!

* Users can sign up, sign in and log out
* Users can use a demo login to try the site
* Users can't use certain feature without logging in

    * Creating messages (Channel Messages, Threads, Direct Messages, Comments)
    * Reacting to messages with emotes
    * User page access including personal threads, mentions, drafts, saved items and files

**Comment by rlim92** [comment]
Hey Eric! Everything looks really good. A few comments below:
- [ ] when hovering over the buttons the cursor doesn't change to a pointer (only when hovering over the links in the button). 
- [ ] when not logged in the top right should show two link/buttons `Sign up` and `GET STARTED`.
- [ ] there should be a border above the `Before you go` section. 
- [ ] the error message pop up is not aligned to the sign up form box. Make sure to have them aligned. Compare across different screen sizes to make sure it stays aligned. 
- [ ] (optional) consider adding a small footer name dropping that it is your creation.

Overall, excellent work.
