### ISSUE TITLE
Channel Review

### ISSUE THREAD

**Issue by ericsmith9161** [ericsmith9161/Szyslak#6]
Hi Rich, just making an issue so you can review my channels MVP

**Comment by rlim92** [comment]
Hey Eric! This is looking really good. Some differences I noticed: 

** Channels **
- [ ] the search bar at the top has some black space to the sides and top of it (maybe a border or not enough width)
- [ ] once i click on a person in the persons tab it doesnt disappear when going to a chat channel.
- [ ] the width on the left/right sidebars are not aligned with Slack's sidebars. 
- [ ] the star seems to be purely visual, should add functionality for that eventually.
- [ ] the focus outline appears on click of the channels sidebar part, remove it so it looks cleaner
- [ ]  on hover of `details` it moves. Also when the right sidebar is active details should have the hover effect on it for that duration
- [ ] remove focus outlines on most clickable elements (the blue outline that appears on click) like the delete channel button
- [ ] theres a good amount of dead links, consider what you can implement and try to take out any that wont have functionality. 

** Live Chat **
- [ ] the messages on hover should have the hover color expand to the width of borders of the chatroom box
- [ ] the message form input should start more offset from the left side. 

Overall really excellent work. The CRUD for channels is completely functional and the live chat is working, just needs some more tweaks in styling.
