### ISSUE TITLE
Live Chat MVP Review

### ISSUE THREAD

**Issue by ericsmith9161** [ericsmith9161/Szyslak#7]
I might as well put this one up here while I'm at it.

**Comment by rlim92** [comment]
Hey Eric!

**Live Chat**
- [ ] the sidebar compared to Slack seems wider
- [ ] there should be some padding to the left of the avatar to have some space between the border
- [ ] the message input (where you can start typing) starts too close to the border
- [ ] didn't mention this earlier but, the channels should have a hashtag in front of them and in the message form placeholder
- [ ] consider adding the ability to edit a message, and eventually delete a message (depending on permissions)
- [ ] message form should be a higher

Overall great job!
